#!/usr/bin/env php
<?php

spl_autoload_register(function ($class_name) {
  include $class_name . '.php';
});

function print_usage()
{
  $usage = "USAGE\n\t./206neutrinos n a h sd\n";
  $usage .= "\nDESCRIPTION\n\t";
  $usage .= "n\tnumber of values\n\t";
  $usage .= "a\tarithmetic mean\n\t";
  $usage .= "h\tharmonic mean\n\t";
  $usage .= "sd\tstandard deviation\n";
  echo $usage;
  return (0);
}

function index($argc, $argv)
{
  if ($argc == 2 && strcmp($argv[1], "-h") == 0)
    return (print_usage());
  if ($argc != 5)
    return (84);

  $err = new Errors();
  if ($err->error_handler($argv) == 84)
    return (84);

  $io = new IO();
  return ($io->run($argv));
}

$ret = index($argc, $argv);

exit($ret);
?>